### ISSUE TITLE
Hook Only Invokes One Job

### ISSUE THREAD

**Issue by william-bautista** [Nerdwin15/stash-jenkins-postreceive-webhook#112]
When a user pushes a commit to multiple branches in the same action, only one job is triggered. For example:

git commit -am "Release 4.1"
git checkout release
git reset --hard origin/release
git merge master
git checkout master
git push origin master release

When the above push action is executed, only the Jenkins job that watches the "master" branch is executed. However, when two push actions are executed (one right after the other), then both jobs execute. For example:

git push origin master
git push origin release

**Comment by mikesir87** [comment]
Sorry for taking a while to get back to you... this is because the code was originally sending only one notification, which made sense before sending the branch and hash information.  Now that that info can be sent, it should support multiple notifications.  

A pull request that was merged recently actually brought this support, so will be in the next release!  Thanks for checking in though!
