### ISSUE TITLE
A push containing updates for two or more branches triggers build for one branch only

### ISSUE THREAD

**Issue by karlins** [Nerdwin15/stash-jenkins-postreceive-webhook#80]
Scenario:
1. Create several Pull Requests in Stash
2. Do commits for the branches in those Pull Requests (different branches, same or different files)
3. Do a push to a remote repository (Stash)

Expected:
Stash Webhook Plugin will send notifications for each update contained in the push 

Observed: 
Only one notification is sent to Jenkins. Jenkins logs demonstrates only one notification received from Stash Webhook Plugin (not sure, but seems to be the first if the list of notifications was sorted alphabetically)

Versions:
Stash: v2.10.1
Stash Webhook Plugin: 2.5.0
Jenkins Git Plugin: 2.2.4

Comments: 
1. Thank you very much for the updates made in 2.5.0! They are keeping us of duplicate builds.
2. Previous version of Webhook sends notification for each branch in a single push
3. Being able to manage sending or not sending SHA is very appreciated

Thank you,
Sergey

**Comment by ppaulis** [comment]
@mikesir87 I can confirm this one. Not only for pull requests but also for a simple push with multiple branches. Very embarassing if you are doing git-flow. A Git-Flow hotfix e.g. always merges back into develop and master branch. So having a second hook-call would be nice.

In fact, I was expecting one call with multiple sha1's and branch names in it, because the key in the call is "branches" and not "branch".. What is the behaviour that we should expect there?

Thanks for the nice plugin! Works great besides this bug!

**Comment by mikesir87** [comment]
Sorry for the slow turnaround on this everyone.  Life's been quite hectic over the past few months.  Update to be coming soon!
