### ISSUE TITLE
How to trigger parameterized jenkins builds

### ISSUE THREAD

**Issue by kzgolden-pba** [Nerdwin15/stash-jenkins-postreceive-webhook#9]
I'm looking for a way to trigger a parameterized jenkins build. Example, I want the name of the branch on which the commit was pushed. 

it would use a url like this:

http://server/job/myjob/buildWithParameters?Branch=Value

(where 'Value' is the name of the branch)

Is that already possible with this plugin?

**Comment by skodumuru** [comment]
I configured one jenkins job as "build with parameter" and default value is "**". Now i have created a new branch to have my changes and pushed to gitHub.  When I pushed my changes jenkns started build for all branches as the default value is "**". Now my requirement is, when i push change to github in a particular branch, only that branch has to be build instead of all. I do not want to configure one jenkin job per branch because i have around 20 branch in my repository. If i remove default value "**" then build is not able to retrieve the branch name to build and because of that build is getting failed. any other option to set only one branch (to which gitHub push is applied) to be build with configuration as "Build with parameters" and "Build when a change is pushed to GitHub".
